name: GetSick
main: me.begreen98.GetSick.GetSick
version: 2.0
description: >
            Get Sick Plugin
commands:
   sick:
      description: This is a demo command.
      permission: GetSick.sick
      permission-message: You don't have permission to make people sick!
   cure:
      description: This is a demo command.
      permission: GetSick.cure
      permission-message: You don't have permission to cure people!
